services:
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    # Reinicia em caso de falha
    restart: always
    ports:
      - "9092:9092"   # Porta cliente Kafka
      - "9093:9093"   # Porta do controlador (uso interno KRaft)
    environment:
      # Configurações KRaft (Kafka sem Zookeeper)
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Opções Kafka adicionais (exemplo: criar tópicos automaticamente)
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/bitnami/kafka                   # Persistência dos logs/metadados do Kafka

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"   # Porta padrão do MongoDB
    volumes:
      - mongo_data:/data/db                        # Persistência dos dados do MongoDB

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"    # Web UI do NameNode HDFS
      - "9000:9000"    # Porta RPC do NameNode (fs.defaultFS)
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name            # Diretório de metadados NameNode (formatado no 1º start)

  hadoop:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop
    restart: always
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - SERVICE_PRECONDITION=namenode:9870         # Espera o NameNode estar de pé (porta 9870) antes de iniciar
    volumes:
      - hadoop_datanode:/hadoop/dfs/data           # Diretório de dados do DataNode
      - ./data:/data

# Definição de volumes nomeados para persistência
volumes:
  kafka_data:
  mongo_data:
  hadoop_namenode:
  hadoop_datanode:
